---

- name: download and install pt-query-digest
  get_url: url=https://percona.com/get/pt-query-digest dest=/usr/bin/pt-query-digest mode=0755

- name: download and install lltsv
  get_url: url=https://github.com/sonots/lltsv/releases/download/v0.7.0/lltsv_linux_amd64 dest=/usr/bin/lltsv mode=0755

- name: check alp installation status
  stat:
    path: /usr/bin/alp
  register: alp_bin
- name: download and install alp
  block:
    - name: download alp
      get_url: url=https://github.com/tkuchiki/alp/releases/download/v1.0.10/alp_linux_amd64.zip dest=/tmp/alp_linux_amd64.zip
    - name: unarchive alp
      unarchive: src=/tmp/alp_linux_amd64.zip dest=/usr/bin mode=0755 copy=no
  when: alp_bin.stat.exists == False

- name: install tools
  copy: src=bin/{{ item }} dest=/usr/bin/{{ item }} owner=root group=root mode=0755
  with_items:
    - logrotate.pl
    - restart.sh
